### ISSUE TITLE
Classic arXiv API start and max_results paging

### ISSUE THREAD

**Issue by mhl10** [arXiv/arxiv-search#259]
Ensure that start and max_results paging works as described in the [documentation](https://arxiv.org/help/api/user-manual#paging).

**Comment by alefnula** [comment]
@mhl10 This is the comparison of the results I'm getting from beta and from local server. Can you please comment and say which ones are important to fix and I'll fix it.

# Feed

## Feed

Beta:
```xml
<feed xmlns="http://www.w3.org/2005/Atom">
```

Local:
```xml
<feed xmlns:arxiv="http://arxiv.org/schemas/atom" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns="http://www.w3.org/2005/Atom">
```

This shouldn't make a difference if people are using an xml parser that supports namespaces, but it will brake the code of people who doesn't. (For example python `xml.etree` doesn't support namespaces.)


## ID

Beta:
```xml
<id>/classic_api/query?search_query=all%3Aelectron&amp;start=0&amp;max_results=50&amp;id_list=</id>
```

Local:
```xml
<id>http://arxiv.org/api/WyBPOs+pRgzCTXTMWhtnbcOmk6g</id>
```

Different generator of the `id`?

## Title

Beta:
```xml
<title type="html">ArXiv Query: search_query=all:electron&amp;id_list=&amp;start=0&amp;max_results=10</title>
```

Local:
```xml
<title>arXiv Query: search_query=all:electron&amp;start=0&amp;max_results=50&amp;id_list=</title>
```

Beta has additional `type="html"` attribute and default value for `max_results=10` new version has it at `50`


## Link

Beta:
```xml
<link href="http://arxiv.org/api/query?search_query%3Dall%3Aelectron%26id_list%3D%26start%3D0%26max_results%3D10" rel="self" type="application/atom+xml"/>
```

Local:
```xml
<link href="/classic_api/query?search_query=all%3Aelectron&amp;start=0&amp;max_results=50&amp;id_list=" type="application/atom+xml"/>
```

New version doesn't escape the `=` sign also we see the difference in default value for `max_results`


## Generator

Beta:
```xml
```

Local:
```xml
<generator uri="http://lkiesow.github.io/python-feedgen" version="0.7.0">python-feedgen</generator>
```

Generator tag is missing on beta.

## Updated

Beta:
```xml
<updated>2020-01-24T00:00:00-05:00</updated>
```

Local:
```xml
<updated>2020-01-24T15:00:18.438304+00:00</updated>
```

Beta gives wrong timestamp and doesn't contain milliseconds. Also time zone is different.


# Entry

## Updated & published

Beta:
```xml
<updated>2001-02-28T20:12:09Z</updated>
```

Local:
```xml
<updated>2020-01-24T15:00:18.448341+00:00</updated>
```


Beta:
```xml
<published>2001-02-28T20:12:09Z</published>
```

Local:
```xml
<published>2017-10-30T08:00:33-04:00</published>
```

Very strange behavior of published showing weird timezone on the local server and different formatting from beta, also beta format is different from `<feed><updated>`.

## PDF Link

Beta:
```xml
<link title="pdf" href="http://arxiv.org/pdf/cond-mat/0102536v1" rel="related" type="application/pdf"/>
```

Local:
```xml
<link href="https://arxiv.org/pdf/1708.00212v2" rel="related" type="application/pdf"/>
```

PDF link missing the `title="pdf"` attribute.


## Author

Beta:
```xml
<author>
    <name>M. Nolan</name>
    <arxiv:affiliation xmlns:arxiv="http://arxiv.org/schemas/atom">NMRC, University College, Cork, Ireland</arxiv:affiliation>
</author>
```

Local:
```xml
<author>
    <name>B. V. Komberg</name>
</author>
```

Local version is missing `affiliation` tag.

**Comment by mhl10** [comment]
Hi @alefnula,

Please see my comments below. I'll follow up on the remaining differences you pointed out in a separate comment. Thanks!

> @mhl10 This is the comparison of the results I'm getting from beta and from local server. Can you please comment and say which ones are important to fix and I'll fix it.
> 
> # Feed
> ## Feed
> Beta:
> 
> ```
> <feed xmlns="http://www.w3.org/2005/Atom">
> ```
> 
> Local:
> 
> ```
> <feed xmlns:arxiv="http://arxiv.org/schemas/atom" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns="http://www.w3.org/2005/Atom">
> ```
> 
> This shouldn't make a difference if people are using an `XML` parser that supports namespaces, but it will brake the code of people who don't. (For example python `xml.etree` doesn't support namespaces.)

I think this is OK to leave as-is.

> 
> ## ID
> Beta:
> 
> ```
> <id>http://arxiv.org/api/WyBPOs+pRgzCTXTMWhtnbcOmk6g</id>
> ```
> 
> Local:
> 
> ```
> <id>/classic_api/query?search_query=all%3Aelectron&amp;start=0&amp;max_results=50&amp;id_list=</id>
> ```
> 
> Different generator of the `id`?

I'm not sure how important this really is, but it looks like in classic this the b64-encoding of the sha1 hash of the uri-encoded query string (everything after `query?`).

> 
> ## Title
> Beta:
> 
> ```
> <title type="html">ArXiv Query: search_query=all:electron&amp;id_list=&amp;start=0&amp;max_results=10</title>
> ```
> 
> Local:
> 
> ```
> <title>arXiv Query: search_query=all:electron&amp;start=0&amp;max_results=50&amp;id_list=</title>
> ```
> 
> Beta has additional `type="html"` attribute and default value for `max_results=10`. New version has it at `50`.

Here it's OK to change the new version to match old (i.e. set `max_results` to 10).

> 
> ## Link
> Beta:
> 
> ```
> <link href="http://arxiv.org/api/query?search_query%3Dall%3Aelectron%26id_list%3D%26start%3D0%26max_results%3D10" rel="self" type="application/atom+xml"/>
> ```
> 
> Local:
> 
> ```
> <link href="/classic_api/query?search_query=all%3Aelectron&amp;start=0&amp;max_results=50&amp;id_list=" type="application/atom+xml"/>
> ```
> 
> New version doesn't escape the `=` sign also we see the difference in default value for `max_results`

New version should probably URI-ecode the `=` sign in case somebody is trying to decode it later.

> 
> ## Generator
> Beta:
> 
> Local:
> 
> ```
> <generator uri="http://lkiesow.github.io/python-feedgen" version="0.7.0">python-feedgen</generator>
> ```
> 
> Generator tag is missing on beta.

I happened to notice this as well and created an issue for it: 
https://github.com/lkiesow/python-feedgen/pull/90

but not sure if a new release has been created yet. It's probably OK for the `generator` tag to remain, for now.

> 
> ## Updated
> Beta:
> 
> ```
> <updated>2020-01-24T00:00:00-05:00</updated>
> ```
> 
> Local:
> 
> ```
> <updated>2020-01-24T15:00:18.438304+00:00</updated>
> ```
> 
> Beta gives wrong timestamp and doesn't contain milliseconds. Also time zone is different.

Strange! New version looks better here.

**Comment by alefnula** [comment]
> > ## ID
> > Beta:
> > ```
> > <id>http://arxiv.org/api/WyBPOs+pRgzCTXTMWhtnbcOmk6g</id>
> > ```
> > Local:
> > ```
> > <id>/classic_api/query?search_query=all%3Aelectron&amp;start=0&amp;max_results=50&amp;id_list=</id>
> > ```
> > Different generator of the `id`?
> 
> I'm not sure how important this really is, but it looks like in classic this the b64-encoding of the sha1 hash of the uri-encoded query string (everything after `query?`).

Confirmed it's the `b64(sha1(complete_query_string))`

```python
base64.b64encode(
    hashlib.sha1(
        b"search_query=all:electron&id_list=&start=0&max_results=10"
    ).digest()
)
```
I'll change the new version to mach this.

> > # Title
> Here it's OK to change the new version to match old (i.e. set `max_results` to 10).

OK!

> > ## Link
> New version should probably URI-ecode the `=` sign in case somebody is trying to decode it later.

OK!

> > ## Updated
> > Beta:
> > ```
> > <updated>2020-01-24T00:00:00-05:00</updated>
> > ```
> > Local:
> > ```
> > <updated>2020-01-24T15:00:18.438304+00:00</updated>
> > ```
> > Beta gives wrong timestamp and doesn't contain milliseconds. Also time zone is different.

> Strange! New version looks better here.

OK, but I would unify all the timestamps then?

Also, should we use a localized version or should I change all of them to UTC?

**Comment by mhl10** [comment]
> OK, but I would unify all the timestamps then?
> 
> Also, should we use a localized version or should I change all of them to UTC?

Yes, let's go with unified timestamps with second-granularity at UTC, so for example:
`2020-01-24T15:00:18Z`

(this is a little bit different from my original suggestion--sorry for creating any confusion)

**Comment by mhl10** [comment]
@alefnula here are my comments on the rest of your entries:

> 
> # Entry
> ## Updated & published
> Beta:
> 
> ```
> <updated>2001-02-28T20:12:09Z</updated>
> ```
> 
> Local:
> 
> ```
> <updated>2020-01-24T15:00:18.448341+00:00</updated>
> ```
> 
> Beta:
> 
> ```
> <published>2001-02-28T20:12:09Z</published>
> ```
> 
> Local:
> 
> ```
> <published>2017-10-30T08:00:33-04:00</published>
> ```
> 
> Very strange behavior of published showing weird timezone on the local server and different formatting from beta, also beta format is different from `<feed><updated>` on beta.

Very strange indeed. I'll look into this more closely and let you know what I find.

> 
> ## PDF Link
> Beta:
> 
> ```
> <link title="pdf" href="http://arxiv.org/pdf/cond-mat/0102536v1" rel="related" type="application/pdf"/>
> ```
> 
> Local:
> 
> ```
> <link href="https://arxiv.org/pdf/1708.00212v2" rel="related" type="application/pdf"/>
> ```
> 
> PDF link missing the `title="pdf"` attribute.

Good catch. The link should have the `title` attribute.

> ## Author
> Beta:
> 
> ```
> <author>
>     <name>M. Nolan</name>
>     <arxiv:affiliation xmlns:arxiv="http://arxiv.org/schemas/atom">NMRC, University College, Cork, Ireland</arxiv:affiliation>
> </author>
> ```
> 
> Local:
> 
> ```
> <author>
>     <name>B. V. Komberg</name>
> </author>
> ```
> 
> Local version is missing `affiliation` tag.

Ah, we should definitely include that! Please let me know if you have trouble finding that.

**Comment by alefnula** [comment]
@mhl10 

About the `start` and `max_results`:

1. `max_results` works correctly but,
2. I get the results in an unpredictable order so `start` doesn't makes any sense.
3. Even if I define a `sortBy` and `sortOrder` i get the results in unpredictable way.

I think we should predefine a `sortOrder` and `sortBy` if they are not provided and open another issue for fixing those alongside with the `start` which will work if we always sort results.
