### ISSUE TITLE
Fix the ordering issue for the classical API

### ISSUE THREAD

**Issue by alefnula** [arXiv/arxiv-search#266]
At the moment the order in which the api gives back items is unpredictable even if we set the `sortBy` fields.

We need to:

1. Define the default `sortBy` key when the user doesn't provided. (I think `submitted_date` is a valid candidate). @mhl10 
2. Fix the ordering issue.

**Comment by alefnula** [comment]
Now that I browsed the code nothing handles the `sortBy` and `sortOrder` query parameters. They are completely ignored in the old API and in the new API. Do you have any documentation on the new API so I can fix it in both places at once?

**Comment by alefnula** [comment]
Also I'll need a list of fields that you allow in the `sortBy` query to be able to validate before I send it to elastic search.

**Comment by mhl10** [comment]
> We need to:
> 
> 1. Define the default `sortBy` key when the user doesn't provided. (I think `submitted_date` is a valid candidate). @mhl10

Let's go with descending relevance for now.

**Comment by mhl10** [comment]
> Also I'll need a list of fields that you allow in the `sortBy` query to be able to validate before I send it to elastic search.

These can just be `relevance`, `lastUpdatedDate`, and `submittedDate`.
