### ISSUE TITLE
Make the base URL for links in the overridable 

### ISSUE THREAD

**Issue by mhl10** [arXiv/arxiv-search#280]
We are using flask's `url_for` to generate links in the responses:
```      
        entry.link(
            {
                "href": url_for(
                    "abs",
                    paper_id=doc["paper_id"],
                    version=doc["version"],
                    _external=True,
                ),
                "type": "text/html",
            }
        )
```
The links are using `APPLICATION_ROOT` for the base URL when generating those links. Usually this is OK, but in this case we always want the base URL to be https://arxiv.org (and independent of `APPLICATION_ROOT`).

**Comment by alefnula** [comment]
I think I fixed it now.
